### ISSUE TITLE
Register/Login Screen: Background Text Issue

### ISSUE THREAD

**Issue by IssacSilva** [ReliablePlumbing/reliable-plumbing#11]
From my iPad - I accessed the website and clicked on the Register button.  When the register form pops up - the text that runs on the middle of the website continues to appear behind the form.  

Device: iPad Air (1st generation)

iOS: 9.3.3 (installing iOS 11.2 now / 12/11/2017 @ 7:42 am pst)

Browsers: Chrome & Safari 

Chrome
![chrome](https://user-images.githubusercontent.com/33473813/33839397-fc7ad720-de46-11e7-8dbe-d19c0944d20c.PNG)

Safari
![safari](https://user-images.githubusercontent.com/33473813/33839410-01ad3954-de47-11e7-9b36-82aa50c4c5ba.PNG)

**Comment by ahmedGomaa90** [comment]
@IssacSilva  could please check this issue if it still exists in any popups in the system
