### ISSUE TITLE
Schedule A Call: Formatting

### ISSUE THREAD

**Issue by IssacSilva** [ReliablePlumbing/reliable-plumbing#12]
When a user/customer wants to schedule a call - please use the formatting/order of the fields below:

1. First Name
2. Last Name
3. Mobile/Telephone
4. Email Address
5. Street Address
6. City
7. State (populate CA automatically - cannot be changed)
8. Zip Code
9. Select a date
10. Time
11. Service
12. Preferred Method of contact (drop-down)
      A. Email
      B. Telephone
13. Upload Image/Take Picture
14. Message (box so customer can enter a detailed message)

**Comment by ahmedGomaa90** [comment]
* could you specify the required fields "for validation" (you can write their numbers)
* the default selected in method of contact.
* explain more about state, what's CA, would it be only one state ?
