### ISSUE TITLE
Login Screen: Formatting

### ISSUE THREAD

**Issue by IssacSilva** [ReliablePlumbing/reliable-plumbing#16]
The login screen/form will need a few formatting changes/updates.  

Changes:
Username / Email = Email 
password = Password
Login = Sign In
forgot password = Forgot Password
remember me = Remember Me

Buttons:
Add Register (see blank red box in image)

Alignment:
the checkbox next to "remember me" is not centered.  Align checkbox with text box.
Move "forgot password" and place above "Login" button.
Drop Login button and place where forgot password is currently located.

Highlighted Areas

![login-form](https://user-images.githubusercontent.com/33473813/33844736-12862024-de56-11e7-9140-0e8634a75447.png)

**Comment by ahmedGomaa90** [comment]
![image](https://user-images.githubusercontent.com/29007104/34457676-237fc2d4-edc1-11e7-90f9-3711a8d11741.png)


@mohamedabdelkader93  make something like this, and place social login properly 

@IssacSilva  I think the form will be neater this way, what do u think?
