### ISSUE TITLE
Schedule Management: Filtering

### ISSUE THREAD

**Issue by IssacSilva** [ReliablePlumbing/reliable-plumbing#24]
Feature/Enhancement: 
When filtering through calls (old and new) - Reliable would like to enable the ability to search via Customer Name.

![image](https://user-images.githubusercontent.com/33473813/36315608-feda4d72-12ec-11e8-920d-13f93f96cc79.png)

**Comment by ahmedGomaa90** [comment]
just realized after deployment there's an UI issue, but the search is working fine, keep the issue open until we fix its UI
