### ISSUE TITLE
Email Notification (Activation) Not Working

### ISSUE THREAD

**Issue by IssacSilva** [ReliablePlumbing/reliable-plumbing#4]
Added the following accounts:
Technician 1: Email@IssacSilva.com 
Technician 2: Me@IssacSilva.com

Emails for both accounts have not been received.  Added accounts at around 7:10 AM (PST) and it is now 7:29 AM - still not email to activate account.

**Comment by ahmedGomaa90** [comment]
this error message appeared in the mail logs, and its from your side, your email is not correctly configured.

![image](https://user-images.githubusercontent.com/29007104/32956256-f5c0d5ee-cbc0-11e7-8ee6-af90e84b807a.png)

**Comment by IssacSilva** [comment]
Thay is why I used a secondary email: Me@IssacSilva.com

Please advise,

Issac Silva

-------- Original message --------
