### ISSUE TITLE
Internet Explorer: Desktop App

### ISSUE THREAD

**Issue by IssacSilva** [ReliablePlumbing/reliable-plumbing#9]
When navigating to the Reliable website (on Amazon servers) on Internet Explorer (desktop app) - the site does not load/open.  I tried locally on my home office computer and logged into another computer - outside my home office network - page does not load/open.

Operating System:
Windows 10

Browser:
Internet Explorer (Desktop app)

**Comment by ahmedGomaa90** [comment]
fixed, but always recommend chrome, Firefox or Edge to our clients, IE is dead and a lost cause.

FYI we only support IE +11
